name: ds-a2-fvc2004-fl
channels:
  - conda-forge
dependencies:
  - python=3.11.9
  - pandas=2.2.2
  - numpy=1.26.4
  - matplotlib=3.8.4
  - scipy=1.13.0
  - scikit-learn=1.4.2
  - pillow=10.3.0
  - pip
  - pip:
      - opencv-python-headless==4.10.0.84
